name: Build Sunlight

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Check SDK
        run: |
         echo "THEOS=$THEOS"
         ls -la "$THEOS/sdks"
         find "$THEOS/sdks" -path "*/Preferences.framework" -print

      - name: Setup Theos
        uses: waruhachi/theos-action@v2.4.6
        with:
          theos-src: theos/theos
          theos-branch: master
          sdks-src: theos/sdks
          sdks-branch: master

      - name: Build Sunlight
        working-directory: SpringBoardWidgetDesigner
        run: make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: Sunlight-deb
          path: SpringBoardWidgetDesigner/packages/*.deb
          if-no-files-found: error
